### ISSUE TITLE
如何将其它App的NLog的信息汇总到一起？

### ISSUE THREAD

**Issue by whsheng** [kerryjiang/LogMaster4Net#3]
关注了LogMaster4Net，但没有看明白，如何将其它App的NLog的信息汇总到一起？
能否提供比较详细的示例？

**Comment by kerryjiang** [comment]
NLog's network target.

Please check out the doc, https://github.com/kerryjiang/LogMaster4Net/blob/master/NLog.md

<target xsi:type="Network"
        name="udp"
        encoding="utf-8"
        address="udp://127.0.0.1:2020"
        layout="${log4jxmlevent:includeSourceInfo=true:includeCallSite=true:includeMDC=true:appInfo=[LogAppName]:includeNDC=true:includeNLogData=true}">
</target>
